// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace meta {
    export namespace v1 {
        /**
         * ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
         */
        export interface ListMeta {
            /**
             * continue may be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a consistent list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response, unless you have received this token from an error message.
             */
            continue?: pulumi.Input<string>;
            /**
             * remainingItemCount is the number of subsequent items in the list which are not included in this list response. If the list request contained label or field selectors, then the number of remaining items is unknown and the field will be left unset and omitted during serialization. If the list is complete (either because it is not chunking or because this is the last chunk), then there are no more remaining items and this field will be left unset and omitted during serialization. Servers older than v1.15 do not set this field. The intended use of the remainingItemCount is *estimating* the size of a collection. Clients should not rely on the remainingItemCount to be set or to be exact.
             */
            remainingItemCount?: pulumi.Input<number>;
            /**
             * String that identifies the server's internal version of this object that can be used by clients to determine when objects have changed. Value must be treated as opaque by clients and passed unmodified back to the server. Populated by the system. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
             */
            resourceVersion?: pulumi.Input<string>;
            /**
             * Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
             */
            selfLink?: pulumi.Input<string>;
        }

        /**
         * ManagedFieldsEntry is a workflow-id, a FieldSet and the group version of the resource that the fieldset applies to.
         */
        export interface ManagedFieldsEntry {
            /**
             * APIVersion defines the version of this resource that this field set applies to. The format is "group/version" just like the top-level APIVersion field. It is necessary to track the version of a field set because it cannot be automatically converted.
             */
            apiVersion?: pulumi.Input<string>;
            /**
             * FieldsType is the discriminator for the different fields format and version. There is currently only one possible value: "FieldsV1"
             */
            fieldsType?: pulumi.Input<string>;
            /**
             * FieldsV1 holds the first JSON version format as described in the "FieldsV1" type.
             */
            fieldsV1?: any;
            /**
             * Manager is an identifier of the workflow managing these fields.
             */
            manager?: pulumi.Input<string>;
            /**
             * Operation is the type of operation which lead to this ManagedFieldsEntry being created. The only valid values for this field are 'Apply' and 'Update'.
             */
            operation?: pulumi.Input<string>;
            /**
             * Subresource is the name of the subresource used to update that object, or empty string if the object was updated through the main resource. The value of this field is used to distinguish between managers, even if they share the same name. For example, a status update will be distinct from a regular update using the same manager name. Note that the APIVersion field is not related to the Subresource field and it always corresponds to the version of the main resource.
             */
            subresource?: pulumi.Input<string>;
            /**
             * Time is the timestamp of when the ManagedFields entry was added. The timestamp will also be updated if a field is added, the manager changes any of the owned fields value or removes a field. The timestamp does not update when a field is removed from the entry because another manager took it over.
             */
            time?: pulumi.Input<string>;
        }

        /**
         * ManagedFieldsEntry is a workflow-id, a FieldSet and the group version of the resource that the fieldset applies to.
         */
        export interface ManagedFieldsEntryPatch {
            /**
             * APIVersion defines the version of this resource that this field set applies to. The format is "group/version" just like the top-level APIVersion field. It is necessary to track the version of a field set because it cannot be automatically converted.
             */
            apiVersion?: pulumi.Input<string>;
            /**
             * FieldsType is the discriminator for the different fields format and version. There is currently only one possible value: "FieldsV1"
             */
            fieldsType?: pulumi.Input<string>;
            /**
             * FieldsV1 holds the first JSON version format as described in the "FieldsV1" type.
             */
            fieldsV1?: any;
            /**
             * Manager is an identifier of the workflow managing these fields.
             */
            manager?: pulumi.Input<string>;
            /**
             * Operation is the type of operation which lead to this ManagedFieldsEntry being created. The only valid values for this field are 'Apply' and 'Update'.
             */
            operation?: pulumi.Input<string>;
            /**
             * Subresource is the name of the subresource used to update that object, or empty string if the object was updated through the main resource. The value of this field is used to distinguish between managers, even if they share the same name. For example, a status update will be distinct from a regular update using the same manager name. Note that the APIVersion field is not related to the Subresource field and it always corresponds to the version of the main resource.
             */
            subresource?: pulumi.Input<string>;
            /**
             * Time is the timestamp of when the ManagedFields entry was added. The timestamp will also be updated if a field is added, the manager changes any of the owned fields value or removes a field. The timestamp does not update when a field is removed from the entry because another manager took it over.
             */
            time?: pulumi.Input<string>;
        }

        /**
         * ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
         */
        export interface ObjectMeta {
            /**
             * Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
             */
            annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
             *
             * Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
             */
            creationTimestamp?: pulumi.Input<string>;
            /**
             * Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.
             */
            deletionGracePeriodSeconds?: pulumi.Input<number>;
            /**
             * DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This field is set by the server when a graceful deletion is requested by the user, and is not directly settable by a client. The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field, once the finalizers list is empty. As long as the finalizers list contains items, deletion is blocked. Once the deletionTimestamp is set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time. For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react by sending a graceful termination signal to the containers in the pod. After that 30 seconds, the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup, remove the pod from the API. In the presence of network partitions, this object may still exist after this timestamp, until an administrator or automated process can determine the resource is fully terminated. If not set, graceful deletion of the object has not been requested.
             *
             * Populated by the system when a graceful deletion is requested. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
             */
            deletionTimestamp?: pulumi.Input<string>;
            /**
             * Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.
             */
            finalizers?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.
             *
             * If this field is specified and the generated name exists, the server will return a 409.
             *
             * Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
             */
            generateName?: pulumi.Input<string>;
            /**
             * A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
             */
            generation?: pulumi.Input<number>;
            /**
             * Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
             */
            labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object.
             */
            managedFields?: pulumi.Input<pulumi.Input<inputs.meta.v1.ManagedFieldsEntry>[]>;
            /**
             * Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
             */
            name?: pulumi.Input<string>;
            /**
             * Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.
             *
             * Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
             */
            namespace?: pulumi.Input<string>;
            /**
             * List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
             */
            ownerReferences?: pulumi.Input<pulumi.Input<inputs.meta.v1.OwnerReference>[]>;
            /**
             * An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.
             *
             * Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
             */
            resourceVersion?: pulumi.Input<string>;
            /**
             * Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
             */
            selfLink?: pulumi.Input<string>;
            /**
             * UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.
             *
             * Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
             */
            uid?: pulumi.Input<string>;
        }

        /**
         * ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
         */
        export interface ObjectMetaPatch {
            /**
             * Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
             */
            annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * CreationTimestamp is a timestamp representing the server time when this object was created. It is not guaranteed to be set in happens-before order across separate operations. Clients may not set this value. It is represented in RFC3339 form and is in UTC.
             *
             * Populated by the system. Read-only. Null for lists. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
             */
            creationTimestamp?: pulumi.Input<string>;
            /**
             * Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.
             */
            deletionGracePeriodSeconds?: pulumi.Input<number>;
            /**
             * DeletionTimestamp is RFC 3339 date and time at which this resource will be deleted. This field is set by the server when a graceful deletion is requested by the user, and is not directly settable by a client. The resource is expected to be deleted (no longer visible from resource lists, and not reachable by name) after the time in this field, once the finalizers list is empty. As long as the finalizers list contains items, deletion is blocked. Once the deletionTimestamp is set, this value may not be unset or be set further into the future, although it may be shortened or the resource may be deleted prior to this time. For example, a user may request that a pod is deleted in 30 seconds. The Kubelet will react by sending a graceful termination signal to the containers in the pod. After that 30 seconds, the Kubelet will send a hard termination signal (SIGKILL) to the container and after cleanup, remove the pod from the API. In the presence of network partitions, this object may still exist after this timestamp, until an administrator or automated process can determine the resource is fully terminated. If not set, graceful deletion of the object has not been requested.
             *
             * Populated by the system when a graceful deletion is requested. Read-only. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
             */
            deletionTimestamp?: pulumi.Input<string>;
            /**
             * Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.
             */
            finalizers?: pulumi.Input<pulumi.Input<string>[]>;
            /**
             * GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.
             *
             * If this field is specified and the generated name exists, the server will return a 409.
             *
             * Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
             */
            generateName?: pulumi.Input<string>;
            /**
             * A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
             */
            generation?: pulumi.Input<number>;
            /**
             * Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
             */
            labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
            /**
             * ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object.
             */
            managedFields?: pulumi.Input<pulumi.Input<inputs.meta.v1.ManagedFieldsEntryPatch>[]>;
            /**
             * Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
             */
            name?: pulumi.Input<string>;
            /**
             * Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.
             *
             * Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
             */
            namespace?: pulumi.Input<string>;
            /**
             * List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
             */
            ownerReferences?: pulumi.Input<pulumi.Input<inputs.meta.v1.OwnerReferencePatch>[]>;
            /**
             * An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.
             *
             * Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
             */
            resourceVersion?: pulumi.Input<string>;
            /**
             * Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
             */
            selfLink?: pulumi.Input<string>;
            /**
             * UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.
             *
             * Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
             */
            uid?: pulumi.Input<string>;
        }

        /**
         * OwnerReference contains enough information to let you identify an owning object. An owning object must be in the same namespace as the dependent, or be cluster-scoped, so there is no namespace field.
         */
        export interface OwnerReference {
            /**
             * API version of the referent.
             */
            apiVersion: pulumi.Input<string>;
            /**
             * If true, AND if the owner has the "foregroundDeletion" finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. See https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion for how the garbage collector interacts with this field and enforces the foreground deletion. Defaults to false. To set this field, a user needs "delete" permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.
             */
            blockOwnerDeletion?: pulumi.Input<boolean>;
            /**
             * If true, this reference points to the managing controller.
             */
            controller?: pulumi.Input<boolean>;
            /**
             * Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind: pulumi.Input<string>;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
             */
            name: pulumi.Input<string>;
            /**
             * UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
             */
            uid: pulumi.Input<string>;
        }

        /**
         * OwnerReference contains enough information to let you identify an owning object. An owning object must be in the same namespace as the dependent, or be cluster-scoped, so there is no namespace field.
         */
        export interface OwnerReferencePatch {
            /**
             * API version of the referent.
             */
            apiVersion?: pulumi.Input<string>;
            /**
             * If true, AND if the owner has the "foregroundDeletion" finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. See https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion for how the garbage collector interacts with this field and enforces the foreground deletion. Defaults to false. To set this field, a user needs "delete" permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.
             */
            blockOwnerDeletion?: pulumi.Input<boolean>;
            /**
             * If true, this reference points to the managing controller.
             */
            controller?: pulumi.Input<boolean>;
            /**
             * Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: pulumi.Input<string>;
            /**
             * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
             */
            name?: pulumi.Input<string>;
            /**
             * UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
             */
            uid?: pulumi.Input<string>;
        }

    }
}

export namespace rabbitmq {
    export namespace v1beta1 {
        /**
         * Permission is the Schema for the permissions API
         */
        export interface Permission {
            /**
             * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: pulumi.Input<"rabbitmq.com/v1beta1">;
            /**
             * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: pulumi.Input<"Permission">;
            /**
             * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
             */
            metadata?: pulumi.Input<inputs.meta.v1.ObjectMeta>;
            spec?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpec>;
            status?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionStatus>;
        }

        /**
         * PermissionSpec defines the desired state of Permission
         */
        export interface PermissionSpec {
            permissions?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpecPermissions>;
            rabbitmqClusterReference?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpecRabbitmqClusterReference>;
            /**
             * Name of an existing user; must provide user or userReference, else create/update will fail; cannot be updated
             */
            user?: pulumi.Input<string>;
            userReference?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpecUserReference>;
            /**
             * Name of an existing vhost; required property; cannot be updated
             */
            vhost?: pulumi.Input<string>;
        }

        /**
         * PermissionSpec defines the desired state of Permission
         */
        export interface PermissionSpecPatch {
            permissions?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpecPermissionsPatch>;
            rabbitmqClusterReference?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpecRabbitmqClusterReferencePatch>;
            /**
             * Name of an existing user; must provide user or userReference, else create/update will fail; cannot be updated
             */
            user?: pulumi.Input<string>;
            userReference?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpecUserReferencePatch>;
            /**
             * Name of an existing vhost; required property; cannot be updated
             */
            vhost?: pulumi.Input<string>;
        }

        /**
         * Permissions to grant to the user in the specific vhost; required property.
         * See RabbitMQ doc for more information: https://www.rabbitmq.com/access-control.html#user-management
         */
        export interface PermissionSpecPermissions {
            configure?: pulumi.Input<string>;
            read?: pulumi.Input<string>;
            write?: pulumi.Input<string>;
        }

        /**
         * Permissions to grant to the user in the specific vhost; required property.
         * See RabbitMQ doc for more information: https://www.rabbitmq.com/access-control.html#user-management
         */
        export interface PermissionSpecPermissionsPatch {
            configure?: pulumi.Input<string>;
            read?: pulumi.Input<string>;
            write?: pulumi.Input<string>;
        }

        /**
         * Reference to the RabbitmqCluster that both the provided user and vhost are.
         * Required property.
         */
        export interface PermissionSpecRabbitmqClusterReference {
            connectionSecret?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpecRabbitmqClusterReferenceConnectionSecret>;
            /**
             * The name of the RabbitMQ cluster to reference.
             * Have to set either name or connectionSecret, but not both.
             */
            name?: pulumi.Input<string>;
            /**
             * The namespace of the RabbitMQ cluster to reference.
             * Defaults to the namespace of the requested resource if omitted.
             */
            namespace?: pulumi.Input<string>;
        }

        /**
         * Secret contains the http management uri for the RabbitMQ cluster.
         * The Secret must contain the key `uri`, `username` and `password` or operator will error.
         * Have to set either name or connectionSecret, but not both.
         */
        export interface PermissionSpecRabbitmqClusterReferenceConnectionSecret {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

        /**
         * Secret contains the http management uri for the RabbitMQ cluster.
         * The Secret must contain the key `uri`, `username` and `password` or operator will error.
         * Have to set either name or connectionSecret, but not both.
         */
        export interface PermissionSpecRabbitmqClusterReferenceConnectionSecretPatch {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

        /**
         * Reference to the RabbitmqCluster that both the provided user and vhost are.
         * Required property.
         */
        export interface PermissionSpecRabbitmqClusterReferencePatch {
            connectionSecret?: pulumi.Input<inputs.rabbitmq.v1beta1.PermissionSpecRabbitmqClusterReferenceConnectionSecretPatch>;
            /**
             * The name of the RabbitMQ cluster to reference.
             * Have to set either name or connectionSecret, but not both.
             */
            name?: pulumi.Input<string>;
            /**
             * The namespace of the RabbitMQ cluster to reference.
             * Defaults to the namespace of the requested resource if omitted.
             */
            namespace?: pulumi.Input<string>;
        }

        /**
         * Reference to an existing user.rabbitmq.com object; must provide user or userReference, else create/update will fail; cannot be updated
         */
        export interface PermissionSpecUserReference {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

        /**
         * Reference to an existing user.rabbitmq.com object; must provide user or userReference, else create/update will fail; cannot be updated
         */
        export interface PermissionSpecUserReferencePatch {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

        /**
         * PermissionStatus defines the observed state of Permission
         */
        export interface PermissionStatus {
            conditions?: pulumi.Input<pulumi.Input<inputs.rabbitmq.v1beta1.PermissionStatusConditions>[]>;
            /**
             * observedGeneration is the most recent successful generation observed for this Permission. It corresponds to the
             * Permission's generation, which is updated on mutation by the API Server.
             */
            observedGeneration?: pulumi.Input<number>;
        }

        export interface PermissionStatusConditions {
            /**
             * The last time this Condition status changed.
             */
            lastTransitionTime?: pulumi.Input<string>;
            /**
             * Full text reason for current status of the condition.
             */
            message?: pulumi.Input<string>;
            /**
             * One word, camel-case reason for current status of the condition.
             */
            reason?: pulumi.Input<string>;
            /**
             * True, False, or Unknown
             */
            status?: pulumi.Input<string>;
            /**
             * Type indicates the scope of the custom resource status addressed by the condition.
             */
            type?: pulumi.Input<string>;
        }

        /**
         * User is the Schema for the users API.
         */
        export interface User {
            /**
             * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
             */
            apiVersion?: pulumi.Input<"rabbitmq.com/v1beta1">;
            /**
             * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
             */
            kind?: pulumi.Input<"User">;
            /**
             * Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
             */
            metadata?: pulumi.Input<inputs.meta.v1.ObjectMeta>;
            spec?: pulumi.Input<inputs.rabbitmq.v1beta1.UserSpec>;
            status?: pulumi.Input<inputs.rabbitmq.v1beta1.UserStatus>;
        }

        /**
         * Spec configures the desired state of the User object.
         */
        export interface UserSpec {
            importCredentialsSecret?: pulumi.Input<inputs.rabbitmq.v1beta1.UserSpecImportCredentialsSecret>;
            rabbitmqClusterReference?: pulumi.Input<inputs.rabbitmq.v1beta1.UserSpecRabbitmqClusterReference>;
            /**
             * List of permissions tags to associate with the user. This determines the level of
             * access to the RabbitMQ management UI granted to the user. Omitting this field will
             * lead to a user than can still connect to the cluster through messaging protocols,
             * but cannot perform any management actions.
             * For more information, see https://www.rabbitmq.com/management.html#permissions.
             */
            tags?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * Defines a Secret used to pre-define the username and password set for this User. User objects created
         * with this field set will not have randomly-generated credentials, and will instead import
         * the username/password values from this Secret.
         * The Secret must contain the keys `username` and `password` in its Data field, or the import will fail.
         * Note that this import only occurs at creation time, and is ignored once a password has been set
         * on a User.
         */
        export interface UserSpecImportCredentialsSecret {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

        /**
         * Defines a Secret used to pre-define the username and password set for this User. User objects created
         * with this field set will not have randomly-generated credentials, and will instead import
         * the username/password values from this Secret.
         * The Secret must contain the keys `username` and `password` in its Data field, or the import will fail.
         * Note that this import only occurs at creation time, and is ignored once a password has been set
         * on a User.
         */
        export interface UserSpecImportCredentialsSecretPatch {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

        /**
         * Spec configures the desired state of the User object.
         */
        export interface UserSpecPatch {
            importCredentialsSecret?: pulumi.Input<inputs.rabbitmq.v1beta1.UserSpecImportCredentialsSecretPatch>;
            rabbitmqClusterReference?: pulumi.Input<inputs.rabbitmq.v1beta1.UserSpecRabbitmqClusterReferencePatch>;
            /**
             * List of permissions tags to associate with the user. This determines the level of
             * access to the RabbitMQ management UI granted to the user. Omitting this field will
             * lead to a user than can still connect to the cluster through messaging protocols,
             * but cannot perform any management actions.
             * For more information, see https://www.rabbitmq.com/management.html#permissions.
             */
            tags?: pulumi.Input<pulumi.Input<string>[]>;
        }

        /**
         * Reference to the RabbitmqCluster that the user will be created for. This cluster must
         * exist for the User object to be created.
         */
        export interface UserSpecRabbitmqClusterReference {
            connectionSecret?: pulumi.Input<inputs.rabbitmq.v1beta1.UserSpecRabbitmqClusterReferenceConnectionSecret>;
            /**
             * The name of the RabbitMQ cluster to reference.
             * Have to set either name or connectionSecret, but not both.
             */
            name?: pulumi.Input<string>;
            /**
             * The namespace of the RabbitMQ cluster to reference.
             * Defaults to the namespace of the requested resource if omitted.
             */
            namespace?: pulumi.Input<string>;
        }

        /**
         * Secret contains the http management uri for the RabbitMQ cluster.
         * The Secret must contain the key `uri`, `username` and `password` or operator will error.
         * Have to set either name or connectionSecret, but not both.
         */
        export interface UserSpecRabbitmqClusterReferenceConnectionSecret {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

        /**
         * Secret contains the http management uri for the RabbitMQ cluster.
         * The Secret must contain the key `uri`, `username` and `password` or operator will error.
         * Have to set either name or connectionSecret, but not both.
         */
        export interface UserSpecRabbitmqClusterReferenceConnectionSecretPatch {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

        /**
         * Reference to the RabbitmqCluster that the user will be created for. This cluster must
         * exist for the User object to be created.
         */
        export interface UserSpecRabbitmqClusterReferencePatch {
            connectionSecret?: pulumi.Input<inputs.rabbitmq.v1beta1.UserSpecRabbitmqClusterReferenceConnectionSecretPatch>;
            /**
             * The name of the RabbitMQ cluster to reference.
             * Have to set either name or connectionSecret, but not both.
             */
            name?: pulumi.Input<string>;
            /**
             * The namespace of the RabbitMQ cluster to reference.
             * Defaults to the namespace of the requested resource if omitted.
             */
            namespace?: pulumi.Input<string>;
        }

        /**
         * Status exposes the observed state of the User object.
         */
        export interface UserStatus {
            conditions?: pulumi.Input<pulumi.Input<inputs.rabbitmq.v1beta1.UserStatusConditions>[]>;
            credentials?: pulumi.Input<inputs.rabbitmq.v1beta1.UserStatusCredentials>;
            /**
             * observedGeneration is the most recent successful generation observed for this User. It corresponds to the
             * User's generation, which is updated on mutation by the API Server.
             */
            observedGeneration?: pulumi.Input<number>;
            /**
             * Provide rabbitmq Username
             */
            username?: pulumi.Input<string>;
        }

        export interface UserStatusConditions {
            /**
             * The last time this Condition status changed.
             */
            lastTransitionTime?: pulumi.Input<string>;
            /**
             * Full text reason for current status of the condition.
             */
            message?: pulumi.Input<string>;
            /**
             * One word, camel-case reason for current status of the condition.
             */
            reason?: pulumi.Input<string>;
            /**
             * True, False, or Unknown
             */
            status?: pulumi.Input<string>;
            /**
             * Type indicates the scope of the custom resource status addressed by the condition.
             */
            type?: pulumi.Input<string>;
        }

        /**
         * Provides a reference to a Secret object containing the user credentials.
         */
        export interface UserStatusCredentials {
            /**
             * Name of the referent.
             * More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
             * TODO: Add other useful fields. apiVersion, kind, uid?
             */
            name?: pulumi.Input<string>;
        }

    }
}
